# Generated by Django 3.1.1 on 2020-09-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200906_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last',
            new_name='last_name',
        ),
    ]
