# Generated by Django 3.1.1 on 2020-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200906_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default='Engineering', max_length=64),
            preserve_default=False,
        ),
    ]
